"""
Re-exports centralizados de los schemas Pydantic.
"""

from app.schemas.agency_schema import (
    AgenciaCreate,
    AgenciaRead,
    AgenciaUpdate,
    ApiKeyCreate,
    ApiKeyRead,
    ApiKeyRevoke,
    ComisionCreate,
    ComisionRead,
    LiquidacionCreate,
    LiquidacionRead,
    LiquidacionUpdate,
    PlanCreate,
    PlanRead,
    SuscripcionCreate,
    SuscripcionRead,
    SuscripcionUpdate,
    TicketSoporteCreate,
    TicketSoporteRead,
    TicketSoporteUpdate,
)
from app.schemas.bus_schema import BusCreate, BusRead, BusUpdate
from app.schemas.claim_schema import (
    MensajeReclamoCreate,
    MensajeReclamoRead,
    ReclamoCreate,
    ReclamoHiloRead,
    ReclamoRead,
    ReclamoRespuestaAdmin,
    ReclamoUpdate,
)
from app.schemas.location_schema import (
    AgenciaTerminalCreate,
    AgenciaTerminalRead,
    DepartamentoRead,
    DistritoRead,
    ProvinciaRead,
    TerminalCreate,
    TerminalRead,
    TipoDocumentoRead,
)
from app.schemas.route_schema import (
    RutaBusquedaResponse,
    RutaCreate,
    RutaFiltros,
    RutaRead,
    RutaUpdate,
    TarifaRutaCreate,
    TarifaRutaRead,
)
from app.schemas.seat_schema import (
    AsientoBulkCreateResponse,
    AsientoCreate,
    AsientoLayoutRequest,
    AsientoMapaItem,
    AsientoRead,
    AsientoUpdate,
    AsientoViajeRead,
    MapaAsientosResponse,
    SeatHoldRequest,
    SeatHoldResult,
    SeatReleaseRequest,
)
from app.schemas.transaction_schema import (
    BloqueoTemporalCreate,
    BloqueoTemporalRead,
    BoletoCreate,
    BoletoDetalleRead,
    BoletoRead,
    BoletoUpdate,
    CheckoutRequest,
    CheckoutResponse,
    PagoCreate,
    PagoRead,
    PagoUpdate,
    ReembolsoCreate,
    ReembolsoRead,
)
from app.schemas.travel_schema import (
    HistorialEstadoCreate,
    HistorialEstadoRead,
    ManifiestoPasajeroItem,
    ManifiestoSutranCreate,
    ManifiestoSutranRead,
    ManifiestoSutranResponse,
    ViajeBusquedaResponse,
    ViajeCreate,
    ViajeFiltros,
    ViajeRead,
    ViajeUpdate,
)
from app.schemas.user_schema import (
    LoginRequest,
    PasajeroCreate,
    PasajeroRead,
    PasajeroUpdate,
    TokenResponse,
    UsuarioCreate,
    UsuarioInDB,
    UsuarioRead,
    UsuarioUpdate,
)

__all__ = [
    # user_schema
    "LoginRequest",
    "PasajeroCreate",
    "PasajeroRead",
    "PasajeroUpdate",
    "TokenResponse",
    "UsuarioCreate",
    "UsuarioInDB",
    "UsuarioRead",
    "UsuarioUpdate",
    # agency_schema
    "AgenciaCreate",
    "AgenciaRead",
    "AgenciaUpdate",
    "ApiKeyCreate",
    "ApiKeyRead",
    "ApiKeyRevoke",
    "ComisionCreate",
    "ComisionRead",
    "LiquidacionCreate",
    "LiquidacionRead",
    "LiquidacionUpdate",
    "PlanCreate",
    "PlanRead",
    "SuscripcionCreate",
    "SuscripcionRead",
    "SuscripcionUpdate",
    "TicketSoporteCreate",
    "TicketSoporteRead",
    "TicketSoporteUpdate",
    # bus_schema
    "BusCreate",
    "BusRead",
    "BusUpdate",
    # claim_schema
    "MensajeReclamoCreate",
    "MensajeReclamoRead",
    "ReclamoCreate",
    "ReclamoHiloRead",
    "ReclamoRead",
    "ReclamoRespuestaAdmin",
    "ReclamoUpdate",
    # location_schema
    "AgenciaTerminalCreate",
    "AgenciaTerminalRead",
    "DepartamentoRead",
    "DistritoRead",
    "ProvinciaRead",
    "TerminalCreate",
    "TerminalRead",
    "TipoDocumentoRead",
    # route_schema
    "RutaBusquedaResponse",
    "RutaCreate",
    "RutaFiltros",
    "RutaRead",
    "RutaUpdate",
    "TarifaRutaCreate",
    "TarifaRutaRead",
    # seat_schema
    "AsientoBulkCreateResponse",
    "AsientoCreate",
    "AsientoLayoutRequest",
    "AsientoMapaItem",
    "AsientoRead",
    "AsientoUpdate",
    "AsientoViajeRead",
    "MapaAsientosResponse",
    "SeatHoldRequest",
    "SeatHoldResult",
    "SeatReleaseRequest",
    # transaction_schema
    "BloqueoTemporalCreate",
    "BloqueoTemporalRead",
    "BoletoCreate",
    "BoletoDetalleRead",
    "BoletoRead",
    "BoletoUpdate",
    "CheckoutRequest",
    "CheckoutResponse",
    "PagoCreate",
    "PagoRead",
    "PagoUpdate",
    "ReembolsoCreate",
    "ReembolsoRead",
    # travel_schema
    "HistorialEstadoCreate",
    "HistorialEstadoRead",
    "ManifiestoPasajeroItem",
    "ManifiestoSutranCreate",
    "ManifiestoSutranRead",
    "ManifiestoSutranResponse",
    "ViajeBusquedaResponse",
    "ViajeCreate",
    "ViajeFiltros",
    "ViajeRead",
    "ViajeUpdate",
]
